# Building image
# Check which docker tags exist for nvidia/cuda https://hub.docker.com/r/nvidia/cuda/tags
# docker build -f Dockerfile_MolFilterGAN --build-arg CUDA=cu117 --build-arg CUDA_VER=11.7.1 --build-arg OS=cudnn8-devel-ubuntu20.04 --build-arg TORCH=1.13.0 .

ARG CUDA_VER
ARG CUDA
ARG OS
ARG TORCH
FROM nvidia/cuda:$CUDA_VER-$OS
# for some reason have to have arg before and after FROM??
ARG DEBIAN_FRONTEND=noninteractive
ARG CUDA_VER
ARG CUDA
ARG TORCH
ENV CUDA_VER ${CUDA_VER}
ENV CUDA_VER ${CUDA}
ENV TORCH ${TORCH}

# Prerequisites
RUN apt-get -y update
RUN apt-get -y install git
RUN apt-get -y install build-essential
RUN apt-get -y install gfortran 
RUN apt-get -y install texinfo
RUN apt-get -y install wget
RUN apt-get -y install vim
RUN apt-get -y install unzip
RUN apt-get install -y curl
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda
ENV PATH="${PATH}:$CONDA_DIR/bin"

RUN conda create "python=3.9" -n MolFilterGAN

SHELL ["conda", "run", "-n", "MolFilterGAN", "/bin/bash", "-c"]

RUN conda install pytorch==${TORCH} pytorch-cuda=11.7 -c pytorch -c nvidia

RUN conda install -c anaconda numpy --yes

RUN conda install -c anaconda pandas --yes

RUN conda install -c conda-forge rdkit --yes

RUN conda install -c conda-forge tensorboardx --yes

RUN conda install -c conda-forge gdown --yes

RUN conda install -c anaconda scikit-learn --yes

RUN git clone https://github.com/MolFilterGAN/MolFilterGAN

WORKDIR /MolFilterGAN

RUN ["conda", "run", "-n", "MolFilterGAN", "gdown", "--folder", "--id", "1uN7a5m1PmhcXfs5OuOXWPbxyF_KKuZ3A"]

WORKDIR /MolFilterGAN/MolFilterGAN_data_and_trained_models

RUN unzip Datasets.zip

RUN unzip PCBA.zip

RUN unzip BenchmarkDatasets.zip

WORKDIR /MolFilterGAN

RUN cp -r MolFilterGAN_data_and_trained_models/* .

RUN conda init bash

RUN echo "conda activate MolFilterGAN" >> ~/.bashrc
