
# docker build -f Dockerfile_mol_filter_gan_cutoff .

FROM continuumio/miniconda3:4.12.0


RUN apt-get update \
 && apt-get install -yq --no-install-recommends \
    p7zip-full \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*


COPY MolFilterGAN_cutoff.py /. 
